language: python
cache: pip
matrix:
  include:
    - python: 2.7
    - python: 3.8
    - arch: arm64
      python: 3.7
    - arch: amd64
      python: 3.7
    - python: 3.6
    - python: 3.5
    - python: pypy
install:
  - "pip install mock"
script: "python -m unittest discover -p *_test.py"
