language: python
cache: pip
arch:
  - amd64
  - arm64
python:
  - "2.7"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "pypy"
install:
  - "pip install mock"
script: "python -m unittest discover -p *_test.py"
